---

x-common: &octoprint-common
  image: octoprint/octoprint
  restart: unless-stopped
  healthcheck:
    test: "curl -f http://localhost/ || exit 1"

services:

  nginx:
    container_name: octoprint-nginx
    <<: *octoprint-common
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - octoprint-i3mega
      - octoprint-cr10
      - octoprint-sv06

  octoprint-i3mega:
    container_name: octoprint-i3mega
    <<: *octoprint-common
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./octoprint/i3mega/:/octoprint/

  octoprint-cr10:
    container_name: octoprint-cr10
    <<: *octoprint-common
    # devices:
    #   - /dev/ttyUSB1:/dev/ttyUSB1
    volumes:
      - ./octoprint/cr10/:/octoprint/

  octoprint-sv06:
    container_name: octoprint-sv06
    <<: *octoprint-common
    # devices:
    #   - /dev/ttyUSB2:/dev/ttyUSB2
    volumes:
      - ./octoprint/sv06/:/octoprint/
